"""
Source Code Summaries model for MongoDB
"""

import logging
from pydantic import Field
from design_task_service.models.base import BaseDocument

logger = logging.getLogger(__name__)


# ===================== Constants & Config =====================
# (No constants needed for this model)


# ===================== Main Model =====================
class SourceCodeSummaries(BaseDocument):
    """Source code summaries model for MongoDB collection"""

    git_revision: str = Field(..., description="GIT revision code")
    summary_info: str = Field(..., description="Summary information generated by LLM")

    class Config:
        collection_name = "source_code_summaries"
        populate_by_name = True
        json_schema_extra = {
            "example": {
                "git_revision": "abc123def456",
                "summary_info": "This function handles user authentication...",
                "created_at": "2025-01-08T10:00:00Z",
                "updated_at": "2025-01-08T10:00:00Z",
                "deleted_at": None,
            }
        }
